package:
  description: "SONATA RING with traffic classifier service for qualification environment"
  maintainer: "Thomas Soenen, imec, thomas.soenen@ugent.be"
  name: sonata-ring-vtc-service
  vendor: eu.sonata-nfv.package
  version: '0.1'
descriptor_extension: "yml"
version: '0.5'
