package:
  description: "SONATA RING with three traffic vring vnf for qualification environment"
  maintainer: "DarioValocchi, UCL, d.valocchi@ucl.ac.uk"
  name: sonata-vring-vring-vring-service
  vendor: eu.sonata-nfv.package
  version: '0.1'
descriptor_extension: "yml"
version: '0.5'
