package:
  description: "SONATA RING service for qualification environment"
  maintainer: "Felipe Vicens, ATOS, felipe.vicens@atos.net"
  name: sonata-ring-service
  vendor: eu.sonata-nfv.package
  version: '0.1'
descriptor_extension: "yml"
version: '0.1'
